export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_FAILURE = 'FETCH_CLASSES_FAILURE';

export const SUBMIT_CLASS_SUCCESS = 'SUBMIT_CLASS_SUCCESS';
export const SUBMIT_CLASS_FAILURE = 'SUBMIT_CLASS_FAILURE';
export const CLASS_MESSAGE_RECEIVED = 'CLASS_MESSAGE_RECEIVED';
