export const FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS';
export const FETCH_CLASSES_FAILURE = 'FETCH_CLASSES_FAILURE';

export const SUBMIT_CLASS_SUCCESS = 'SUBMIT_CLASS_SUCCESS';
export const SUBMIT_CLASS_FAILURE = 'SUBMIT_CLASS_FAILURE';
export const MESSAGE_RECEIVED = 'MESSAGE_RECEIVED';

export const SET_IS_FETCHING = 'SET_IS_FETCHING';
export const SET_IS_SAVING = 'SET_IS_SAVING';

export const DESERIALIZE_CLASSES = 'DESERIALIZE_CLASSES';
